package dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import database.ProcedureCaller;
import database.ViewLoader;
import models.ExpiredDocumentAlert;

/**
 * ExpiredDocumentAlertDAO - Uses ONLY stored procedures and views for all operations.
 *
 * @author Vehicle Identification System Team
 * @version 2.0
 */
public class ExpiredDocumentAlertDAO extends BaseDAO<ExpiredDocumentAlert> {

    private final ProcedureCaller procedureCaller;
    private final ViewLoader viewLoader;

    public ExpiredDocumentAlertDAO() {
        this.procedureCaller = new ProcedureCaller();
        this.viewLoader = new ViewLoader();
    }

    @Override
    public ExpiredDocumentAlert findById(int id) throws SQLException {
        List<Map<String, Object>> results = viewLoader.loadViewWithCondition("vw_expired_documents", "id = ?", id);
        if (results.isEmpty()) {
            return null;
        }
        return mapToExpiredDocumentAlert(results.get(0));
    }

    @Override
    public List<ExpiredDocumentAlert> findAll() throws SQLException {
        List<Map<String, Object>> results = viewLoader.loadView("vw_expired_documents");
        return mapToExpiredDocumentAlertList(results);
    }

    public List<ExpiredDocumentAlert> findByVehicleId(int vehicleId) throws SQLException {
        List<Map<String, Object>> results = viewLoader.loadViewWithCondition("vw_expired_documents", "vehicle_id = ? ORDER BY expiry_date", vehicleId);
        return mapToExpiredDocumentAlertList(results);
    }

    public List<ExpiredDocumentAlert> findByAlertLevel(String alertLevel) throws SQLException {
        List<Map<String, Object>> results = viewLoader.loadViewWithCondition("vw_expired_documents", "expiry_status = ? ORDER BY expiry_date", alertLevel);
        return mapToExpiredDocumentAlertList(results);
    }

    public List<ExpiredDocumentAlert> findCriticalAlerts() throws SQLException {
        List<Map<String, Object>> results = viewLoader.loadViewWithCondition("vw_expired_documents", "expiry_status IN ('EXPIRED', 'CRITICAL') ORDER BY expiry_date");
        return mapToExpiredDocumentAlertList(results);
    }

    public List<ExpiredDocumentAlert> findExpiringWithinDays(int days) throws SQLException {
        List<Map<String, Object>> results = viewLoader.loadViewWithCondition("vw_vehicle_document_expiry",
                "expiry_date BETWEEN CURRENT_DATE AND CURRENT_DATE + ? ORDER BY expiry_date", days);
        return mapToExpiredDocumentAlertList(results);
    }

    /**
     * Finds documents expiring within the specified number of days.
     *
     * @param days the number of days to look ahead
     * @return list of expired document alerts
     * @throws SQLException if database error occurs
     */
    public List<ExpiredDocumentAlert> findDocumentsExpiringWithin(int days) throws SQLException {
        return findExpiringWithinDays(days);
    }

    /**
     * Gets the count of vehicles with expired documents.
     *
     * @return number of vehicles with expired documents
     * @throws SQLException if database error occurs
     */
    public int getVehiclesWithExpiredDocuments() throws SQLException {
        // Count distinct vehicles with expired documents
        List<Map<String, Object>> results = viewLoader.loadViewWithCondition("vw_expired_documents", "1=1");
        if (results == null || results.isEmpty()) {
            return 0;
        }
        // Get distinct vehicle IDs
        return (int) results.stream().map(m -> m.get("vehicle_id")).distinct().count();
    }

    public void checkVehicleDocuments(String registrationNumber) throws SQLException {
        procedureCaller.executeCheckVehicleDocuments(registrationNumber);
    }

    public void runExpiredDocumentDetection() throws SQLException {
        procedureCaller.executeDetectExpiredDocuments();
    }

    public void generateViolationsForExpiredDocuments() throws SQLException {
        procedureCaller.executeGenerateExpiredDocumentViolations();
    }

    @Override
    public boolean insert(ExpiredDocumentAlert entity) throws SQLException {
        // Alerts are auto-generated by procedures
        return false;
    }

    @Override
    public boolean update(ExpiredDocumentAlert entity) throws SQLException {
        // Alerts are auto-generated by procedures
        return false;
    }

    @Override
    public boolean delete(int id) throws SQLException {
        return procedureCaller.executeDeleteExpiredDocumentAlert(id);
    }

    public int countExpiredDocuments() throws SQLException {
        return viewLoader.countViewRows("vw_expired_documents");
    }

    public int countExpiringDocuments(int days) throws SQLException {
        return viewLoader.countViewRowsWithCondition("vw_vehicle_document_expiry",
                "expiry_date BETWEEN CURRENT_DATE AND CURRENT_DATE + ?", days);
    }

    // ============================================
    // HELPER METHODS FOR MAPPING
    // ============================================

    private ExpiredDocumentAlert mapToExpiredDocumentAlert(Map<String, Object> map) {
        if (map == null) return null;

        ExpiredDocumentAlert alert = new ExpiredDocumentAlert();

        if (map.get("id") != null) alert.setId(((Number) map.get("id")).intValue());
        if (map.get("vehicle_id") != null) alert.setVehicleId(((Number) map.get("vehicle_id")).intValue());
        if (map.get("registration_number") != null) alert.setRegistrationNumber(map.get("registration_number").toString());
        if (map.get("make") != null) alert.setMake(map.get("make").toString());
        if (map.get("model") != null) alert.setModel(map.get("model").toString());
        if (map.get("document_type") != null) alert.setDocumentType(map.get("document_type").toString());
        if (map.get("document_number") != null) alert.setDocumentNumber(map.get("document_number").toString());

        if (map.get("issue_date") != null) {
            Object dateObj = map.get("issue_date");
            if (dateObj instanceof java.sql.Date) {
                alert.setIssueDate(((java.sql.Date) dateObj).toLocalDate());
            } else if (dateObj instanceof LocalDate) {
                alert.setIssueDate((LocalDate) dateObj);
            }
        }
        if (map.get("expiry_date") != null) {
            Object dateObj = map.get("expiry_date");
            if (dateObj instanceof java.sql.Date) {
                alert.setExpiryDate(((java.sql.Date) dateObj).toLocalDate());
            } else if (dateObj instanceof LocalDate) {
                alert.setExpiryDate((LocalDate) dateObj);
            }
        }

        if (alert.getExpiryDate() != null) {
            long daysOverdue = java.time.temporal.ChronoUnit.DAYS.between(alert.getExpiryDate(), LocalDate.now());
            alert.setDaysOverdue((int) Math.max(0, daysOverdue));
        }

        String expiryStatus = map.get("expiry_status") != null ? map.get("expiry_status").toString() : "";
        if ("EXPIRED".equals(expiryStatus)) {
            alert.setAlertLevel("CRITICAL");
            alert.setRecommendedAction("IMMEDIATE_VEHICLE_IMPOUND");
        } else if ("CRITICAL".equals(expiryStatus)) {
            alert.setAlertLevel("HIGH");
            alert.setRecommendedAction("ON_THE_SPOT_FINE");
        } else if ("WARNING".equals(expiryStatus)) {
            alert.setAlertLevel("MEDIUM");
            alert.setRecommendedAction("WARNING_NOTICE");
        } else if ("DUE_SOON".equals(expiryStatus)) {
            alert.setAlertLevel("LOW");
            alert.setRecommendedAction("REMINDER");
        } else {
            alert.setAlertLevel("NONE");
            alert.setRecommendedAction("NO_ACTION");
        }

        alert.setNotified(false);

        if (map.get("created_at") instanceof java.sql.Timestamp) {
            alert.setCreatedAt(((java.sql.Timestamp) map.get("created_at")).toLocalDateTime());
        }
        if (map.get("updated_at") instanceof java.sql.Timestamp) {
            alert.setUpdatedAt(((java.sql.Timestamp) map.get("updated_at")).toLocalDateTime());
        }

        return alert;
    }

    private List<ExpiredDocumentAlert> mapToExpiredDocumentAlertList(List<Map<String, Object>> maps) {
        List<ExpiredDocumentAlert> alerts = new ArrayList<>();
        if (maps != null) {
            for (Map<String, Object> map : maps) {
                ExpiredDocumentAlert alert = mapToExpiredDocumentAlert(map);
                if (alert != null) {
                    alerts.add(alert);
                }
            }
        }
        return alerts;
    }

    @Override
    protected ExpiredDocumentAlert mapRow(ResultSet rs) throws SQLException {
        ExpiredDocumentAlert alert = new ExpiredDocumentAlert();
        alert.setId(rs.getInt("id"));
        alert.setVehicleId(rs.getInt("vehicle_id"));
        alert.setRegistrationNumber(rs.getString("registration_number"));
        alert.setMake(rs.getString("make"));
        alert.setModel(rs.getString("model"));
        alert.setDocumentType(rs.getString("document_type"));
        alert.setDocumentNumber(rs.getString("document_number"));

        if (rs.getDate("issue_date") != null) {
            alert.setIssueDate(rs.getDate("issue_date").toLocalDate());
        }
        if (rs.getDate("expiry_date") != null) {
            alert.setExpiryDate(rs.getDate("expiry_date").toLocalDate());
        }

        if (alert.getExpiryDate() != null) {
            long daysOverdue = java.time.temporal.ChronoUnit.DAYS.between(alert.getExpiryDate(), LocalDate.now());
            alert.setDaysOverdue((int) Math.max(0, daysOverdue));
        }

        String expiryStatus = rs.getString("expiry_status");
        if ("EXPIRED".equals(expiryStatus)) {
            alert.setAlertLevel("CRITICAL");
            alert.setRecommendedAction("IMMEDIATE_VEHICLE_IMPOUND");
        } else if ("CRITICAL".equals(expiryStatus)) {
            alert.setAlertLevel("HIGH");
            alert.setRecommendedAction("ON_THE_SPOT_FINE");
        } else if ("WARNING".equals(expiryStatus)) {
            alert.setAlertLevel("MEDIUM");
            alert.setRecommendedAction("WARNING_NOTICE");
        } else if ("DUE_SOON".equals(expiryStatus)) {
            alert.setAlertLevel("LOW");
            alert.setRecommendedAction("REMINDER");
        } else {
            alert.setAlertLevel("NONE");
            alert.setRecommendedAction("NO_ACTION");
        }

        alert.setNotified(false);

        if (rs.getTimestamp("created_at") != null) {
            alert.setCreatedAt(rs.getTimestamp("created_at").toLocalDateTime());
        }
        if (rs.getTimestamp("updated_at") != null) {
            alert.setUpdatedAt(rs.getTimestamp("updated_at").toLocalDateTime());
        }
        return alert;
    }
}